/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* NOTE: This file is deprecated. Use .env and src/utils/supabase/client.ts instead */

export const projectId = "gketmjcxsnzrrzwfrxfw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZXRtamN4c256cnJ6d2ZyeGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMzgwNTEsImV4cCI6MjA3NzYxNDA1MX0.kjHxmLRjVyt8cSq9HXuz12TOVk32FdRY0ylbRju_gjw"